apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    uid: cloud_tpu_lab_loki
    url: http://loki:3100
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: cloud_tpu_lab_tempo
          matcherRegex: "\"trace_id\"\\s*:\\s*\"([^\"]+)\""
          name: trace_id
          url: "$${__value.raw}"
